### ISSUE TITLE
CUDA Triton Error - Device Kernel is invalid 

### ISSUE THREAD

**Issue by NoahHenrikKleinschmidt** [MPI-Dortmund/tomotwin-cryoet#114]
Hi there, 

I am trying to run TomoTwin on our cluster. A colleague of mine had a version installed that was working on our server some time ago, but the environment has since been removed, so here I am trying to get it to work again. I followed the installation tutorial from the docs to the latter, and that part went smoothly. However, when I try to run `tomotwin_embed.py`, I get an error related to CUDA. 

In short, the error states:

```
[traceback stuff ...]
torch._dynamo.exc.BackendCompilerFailed: backend='compile_fn' raised:
RuntimeError: Triton Error [CUDA]: device kernel image is invalid
```

<details>
<summary>Full Traceback</summary>

```
Latest version of TomoTwin is installed :-)
Found 1 GPU(s). Start DDP + Compiling.
reading tomotwin/pretrained/tomotwin_v092023.pth
/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/tomotwin/modules/inference/embedor.py:178: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(self.weightspth)
Model config:
{'identifier': 'SiameseNet', 'network_config': {'output_channels': 32, 'dropout': 0.2, 'repeat_layers': 0, 'norm_name': 'GroupNorm', 'norm_kwargs': {'num_groups': 64, 'num_channels': 1024}, 'gem_pooling_p': 0}, 'train_config': {'loss': 'TripletLoss', 'tl_margin': 0.539, 'miner': True, 'miner_margin': 0.734, 'learning_rate': 5.945e-05, 'optimizer': 'Adam', 'weight_decay': 0, 'batchsize': 35, 'patience': 50, 'aug_train_shift_distance': 2}, 'distance': 'COSINE', 'window_size': (37, 37, 37)}
Traceback (most recent call last):
  File "/home/noahhk/miniforge3/envs/tomotwin/bin/tomotwin_embed.py", line 8, in <module>
    sys.exit(_main_())
             ^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/tomotwin/embed_main.py", line 266, in _main_
    start(config)
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/tomotwin/embed_main.py", line 254, in start
    run_distr(config, world_size)
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/tomotwin/embed_main.py", line 240, in run_distr
    mp.spawn(
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 328, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 284, in start_processes
    while not context.join():
              ^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 203, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1446, in _call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/backends/distributed.py", line 546, in compile_fn
    submod_compiler.run(*example_inputs)
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/fx/interpreter.py", line 146, in run
    self.env[node] = self.run_node(node)
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/backends/distributed.py", line 266, in run_node
    compiled_submod_real = self.compile_submod(real_mod, new_args, kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/backends/distributed.py", line 181, in compile_submod
    self.compiler(input_mod, args),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/repro/after_dynamo.py", line 129, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/__init__.py", line 2235, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1253, in compile_fx
    return compile_fx(
           ^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1521, in compile_fx
    return aot_autograd(
           ^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/backends/common.py", line 72, in __call__
    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 1071, in aot_module_simplified
    compiled_fn = dispatch_and_compile()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 1056, in dispatch_and_compile
    compiled_fn, _ = create_aot_dispatcher_function(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 522, in create_aot_dispatcher_function
    return _create_aot_dispatcher_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 759, in _create_aot_dispatcher_function
    compiled_fn, fw_metadata = compiler_fn(
                               ^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 179, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1350, in fw_compiler_base
    return _fw_compiler_base(model, example_inputs, is_inference)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1421, in _fw_compiler_base
    return inner_compile(
           ^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 475, in compile_fx_inner
    return wrap_compiler_debug(_compile_fx_inner, compiler_name="inductor")(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/repro/after_aot.py", line 85, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 661, in _compile_fx_inner
    compiled_graph = FxGraphCache.load(
                     ^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_inductor/codecache.py", line 1334, in load
    compiled_graph = compile_fx_fn(
                     ^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 570, in codegen_and_compile
    compiled_graph = fx_codegen_and_compile(gm, example_inputs, **fx_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 878, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_inductor/graph.py", line 1913, in compile_to_fn
    return self.compile_to_module().call
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_inductor/graph.py", line 1839, in compile_to_module
    return self._compile_to_module()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_inductor/graph.py", line 1867, in _compile_to_module
    mod = PyCodeCache.load_by_key_path(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_inductor/codecache.py", line 2876, in load_by_key_path
    mod = _reload_python_module(key, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_inductor/runtime/compile_tasks.py", line 45, in _reload_python_module
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_noahhk/q5/cq57qr4zll44u4i6ilows7bmnsovauwhpl3ft2o2qdvdpi4js5eb.py", line 542, in <module>
    async_compile.wait(globals())
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_inductor/async_compile.py", line 276, in wait
    scope[key] = result.result()
                 ^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_inductor/codecache.py", line 3344, in result
    self.kernel.precompile()
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 244, in precompile
    compiled_binary, launcher = self._precompile_config(
                                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 452, in _precompile_config
    binary._init_handles()
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/triton/compiler/compiler.py", line 376, in _init_handles
    self.module, self.function, self.n_regs, self.n_spills = driver.active.utils.load_binary(
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Triton Error [CUDA]: device kernel image is invalid

While executing %submod_0 : [num_users=1] = call_module[target=submod_0](args = (%l_inputtensor_, %l_self_modules_conv_layer0_modules_0_parameters_weight_, %l_self_modules_conv_layer0_modules_0_parameters_bias_, %l_self_modules_conv_layer0_modules_1_parameters_weight_, %l_self_modules_conv_layer0_modules_1_parameters_bias_, %l_self_modules_conv_layer0_modules_3_parameters_weight_, %l_self_modules_conv_layer0_modules_3_parameters_bias_, %l_self_modules_conv_layer1_modules_0_parameters_weight_, %l_self_modules_conv_layer1_modules_0_parameters_bias_, %l_self_modules_conv_layer1_modules_1_parameters_weight_, %l_self_modules_conv_layer1_modules_1_parameters_bias_), kwargs = {})
Original traceback:
None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 90, in _wrap
    fn(i, *args)
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/tomotwin/embed_main.py", line 220, in run
    embed_tomogram(tomo, embedor, conf, window_size, mask)
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/tomotwin/embed_main.py", line 148, in embed_tomogram
    embeddings = sliding_window_embedding(tomo=tomo, boxer=boxer, embedor=embedor)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/tomotwin/embed_main.py", line 45, in sliding_window_embedding
    embeddings = embedor.embed(volume_data=boxes)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/tomotwin/modules/inference/embedor.py", line 236, in embed
    subvolume = self.model.forward(subvolume).type(torch.HalfTensor)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 1643, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 1459, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 465, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 1263, in __call__
    return hijacked_callback(
           ^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 1064, in __call__
    result = self._inner_convert(
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 526, in __call__
    return _compile(
           ^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 924, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 666, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_utils_internal.py", line 87, in wrapper_function
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 699, in _compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/bytecode_transformation.py", line 1322, in transform_code_object
    transformations(instructions, code_options)
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 219, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 634, in transform
    tracer.run()
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2796, in run
    super().run()
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 983, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 895, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2987, in RETURN_VALUE
    self._return(inst)
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2972, in _return
    self.output.compile_subgraph(
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1117, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1369, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1416, in call_user_compiler
    return self._call_user_compiler(gm)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahhk/miniforge3/envs/tomotwin/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1465, in _call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: backend='compile_fn' raised:
RuntimeError: Triton Error [CUDA]: device kernel image is invalid

While executing %submod_0 : [num_users=1] = call_module[target=submod_0](args = (%l_inputtensor_, %l_self_modules_conv_layer0_modules_0_parameters_weight_, %l_self_modules_conv_layer0_modules_0_parameters_bias_, %l_self_modules_conv_layer0_modules_1_parameters_weight_, %l_self_modules_conv_layer0_modules_1_parameters_bias_, %l_self_modules_conv_layer0_modules_3_parameters_weight_, %l_self_modules_conv_layer0_modules_3_parameters_bias_, %l_self_modules_conv_layer1_modules_0_parameters_weight_, %l_self_modules_conv_layer1_modules_0_parameters_bias_, %l_self_modules_conv_layer1_modules_1_parameters_weight_, %l_self_modules_conv_layer1_modules_1_parameters_bias_), kwargs = {})
Original traceback:
None

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```
</details>

The full traceback suggests that setting `torch._dynamo.config.suppress_errors = True` should suppress the problem (I cannot confirm that though, since I haven't actually tried yet). 

Anyway, I wanted to ask what you think of this and what fixes you would suggest. It may well be unrelated to TomoTwin itself and be a driver issue or something on our server's side of things, but I wouldn't know of any changes or updates that were made since my colleague had a working version a couple of months ago. 

Technical notes:
- TomoTwin v0.9.1
- Pytorch v2.5.0
- CUDA 11.8 (trying to run on an A5000, which was successful for my colleague)

Things I've tried so far:
- asking my colleague (they don't know either 🥲)
- reinstall the environments with both `conda` and `mamba` (you never know...)
- manually (re-)install the Pytorch dependencies for our system
- try different versions of TomoTwin (0.9.1, 0.7.0, and 0.6.0 only)
- create this issue on GitHub 😉 

Thanks a lot already!
Noah 🌻

**Comment by thorstenwagner** [comment]
seems to be solved, inactive
