### ISSUE TITLE
boxmanager doesn't open

### ISSUE THREAD

**Issue by azazellochg** [MPI-Dortmund/tomotwin-cryoet#59]
Running command: ```source /public/EM/Scipion/conda.rc&& conda activate napari-0.4.4 && napari_boxmanager Runs/000002_ProtImportTomograms/extra/tomo.mrc Runs/000247_ProtTomoTwinRefPicking/extra/tomo/locate/located.tloc```

```
Traceback (most recent call last):
File "/public/EM/Scipion/miniconda3/envs/napari-0.4.4/bin/napari", line 10, in <module>
sys.exit(main())
File "/public/EM/Scipion/miniconda3/envs/napari-0.4.4/lib/python3.10/site-packages/napari/__main__.py", line 561, in main
_run()
File "/public/EM/Scipion/miniconda3/envs/napari-0.4.4/lib/python3.10/site-packages/napari/__main__.py", line 341, in _run
viewer._window._qt_viewer._qt_open(
File "/public/EM/Scipion/miniconda3/envs/napari-0.4.4/lib/python3.10/site-packages/napari/_qt/qt_viewer.py", line 830, in _qt_open
self.viewer.open(
File "/public/EM/Scipion/miniconda3/envs/napari-0.4.4/lib/python3.10/site-packages/napari/components/viewer_model.py", line 1014, in open
self._add_layers_with_plugins(
File "/public/EM/Scipion/miniconda3/envs/napari-0.4.4/lib/python3.10/site-packages/napari/components/viewer_model.py", line 1216, in _add_layers_with_plugins
layer_data, hookimpl = read_data_with_plugins(
File "/public/EM/Scipion/miniconda3/envs/napari-0.4.4/lib/python3.10/site-packages/napari/plugins/io.py", line 77, in read_data_with_plugins
res = _npe2.read(paths, plugin, stack=stack)
File "/public/EM/Scipion/miniconda3/envs/napari-0.4.4/lib/python3.10/site-packages/napari/plugins/_npe2.py", line 55, in read
layer_data, reader = io_utils.read_get_reader(
File "/public/EM/Scipion/miniconda3/envs/napari-0.4.4/lib/python3.10/site-packages/npe2/io_utils.py", line 66, in read_get_reader
return _read(
File "/public/EM/Scipion/miniconda3/envs/napari-0.4.4/lib/python3.10/site-packages/npe2/io_utils.py", line 172, in _read
if layer_data := read_func(paths, stack=stack):
File "/public/EM/Scipion/miniconda3/envs/napari-0.4.4/lib/python3.10/site-packages/npe2/manifest/contributions/_readers.py", line 60, in npe1_compat
return callable_(path)  # type: ignore
File "/public/EM/Scipion/miniconda3/envs/napari-0.4.4/lib/python3.10/site-packages/box_manager/io/mrc.py", line 49, in to_napari
layer_data = to_napari_image(
File "/public/EM/Scipion/miniconda3/envs/napari-0.4.4/lib/python3.10/site-packages/box_manager/io/io_utils.py", line 265, in to_napari_image
metadata["pixel_spacing"] = get_pixel_size(path[0])
IndexError: list index out of range
```

Here is the tloc file:
https://mrclmbcamacuk.sharepoint.com/:u:/s/EMFacility/EfksdZpb-stJsukM2v4A9mUB1Xk_0tjaUPcqp4xNPdfZUw?e=vCfFkz

Is it corrupted?

**Comment by thorstenwagner** [comment]
I have seen this error before. The tloc is not the problem. I can load it with the latest version of boxmanager without any problems. According to the error message, the tomogram is the problem. Are you sure that 'Runs/000002_ProtImportTomograms/extra/tomo.mrc' exists? Can you upload it?

**Comment by thorstenwagner** [comment]
Here is the error message I get when I try to open a non existing file:

```
napari_boxmanager does_not_exist.mrc located.tloc 
Traceback (most recent call last):
  File "/opt/user_software/miniconda3_envs/napari-tomotwin/bin/napari", line 10, in <module>
    sys.exit(main())
  File "/opt/user_software/miniconda3_envs/napari-tomotwin/lib/python3.10/site-packages/napari/__main__.py", line 561, in main
    _run()
  File "/opt/user_software/miniconda3_envs/napari-tomotwin/lib/python3.10/site-packages/napari/__main__.py", line 341, in _run
    viewer._window._qt_viewer._qt_open(
  File "/opt/user_software/miniconda3_envs/napari-tomotwin/lib/python3.10/site-packages/napari/_qt/qt_viewer.py", line 830, in _qt_open
    self.viewer.open(
  File "/opt/user_software/miniconda3_envs/napari-tomotwin/lib/python3.10/site-packages/napari/components/viewer_model.py", line 1014, in open
    self._add_layers_with_plugins(
  File "/opt/user_software/miniconda3_envs/napari-tomotwin/lib/python3.10/site-packages/napari/components/viewer_model.py", line 1216, in _add_layers_with_plugins
    layer_data, hookimpl = read_data_with_plugins(
  File "/opt/user_software/miniconda3_envs/napari-tomotwin/lib/python3.10/site-packages/napari/plugins/io.py", line 77, in read_data_with_plugins
    res = _npe2.read(paths, plugin, stack=stack)
  File "/opt/user_software/miniconda3_envs/napari-tomotwin/lib/python3.10/site-packages/napari/plugins/_npe2.py", line 55, in read
    layer_data, reader = io_utils.read_get_reader(
  File "/home/twagner/.local/lib/python3.10/site-packages/npe2/io_utils.py", line 66, in read_get_reader
    return _read(
  File "/home/twagner/.local/lib/python3.10/site-packages/npe2/io_utils.py", line 165, in _read
    if layer_data := read_func(paths, stack=stack):
  File "/home/twagner/.local/lib/python3.10/site-packages/npe2/manifest/contributions/_readers.py", line 60, in npe1_compat
    return callable_(path)  # type: ignore
  File "/opt/user_software/miniconda3_envs/napari-tomotwin/lib/python3.10/site-packages/box_manager/io/mrc.py", line 49, in to_napari
    layer_data = to_napari_image(
  File "/opt/user_software/miniconda3_envs/napari-tomotwin/lib/python3.10/site-packages/box_manager/io/io_utils.py", line 265, in to_napari_image
    metadata["pixel_spacing"] = get_pixel_size(path[0])

```

To be honest... that's a real bad error message. I gonna change that with the next version.

**Comment by thorstenwagner** [comment]
@azazellochg have you time to check if that was the problem? :-)

**Comment by azazellochg** [comment]
Hi, looking at it now. Runs/000002_ProtImportTomograms/extra/tomo.mrc is a symlink to an existing file. Is napari not resolving links? Anyway, I have tons of other graphics errors when opening napari in remote vnc...

**Comment by thorstenwagner** [comment]
I can open symlinked tomograms:
```
mkdir symtomo
ln -rs tomos/mytomo.mrc symtomo/
napari_boxmanager symtomo/mytomo.mrc
```
works...

**Comment by azazellochg** [comment]
I'll need to check this on a different PC, will try this weekend

**Comment by azazellochg** [comment]
you were right, wrong tomo path
