### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by azazellochg** [MPI-Dortmund/tomotwin-cryoet#6]
Hi @thorstenwagner !
You got io folder and io.py in the same location, and you imported io folder as a module.

```
Traceback (most recent call last):
  File "/home/gsharov/soft/miniconda3/envs/tomotwin-0.2.2b4/bin/tomotwin_embed.py", line 33, in <module>
    sys.exit(load_entry_point('tomotwin-cryoet', 'console_scripts', 'tomotwin_embed.py')())
  File "/home/gsharov/soft/scipion3/software/em/tomotwin-0.2.2b4/tomotwin/embed_main.py", line 506, in _main_
    embeddings = volume_embedding(paths, embedor=embedor)
  File "/home/gsharov/soft/scipion3/software/em/tomotwin-0.2.2b4/tomotwin/embed_main.py", line 407, in volume_embedding
    volume_dataset = FileNameVolumeDataset(volumes=volume_pths, filereader=io.read_mrc)
AttributeError: module 'tomotwin.modules.common.io' has no attribute 'read_mrc'
```

**Comment by thorstenwagner** [comment]
Happy new year and thanks @azazellochg ! I'm sick but I will have a look this week.

**Comment by thorstenwagner** [comment]
Fixed :-) Thanks again for reporting!
